[package]
name = "aprilquest"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
regex = "1.5.5"
futures = "0.3.21"
actix-web = "4.0.1"
derive_more = "0.99.17"
serde = { version = "1.0", features = ["derive"] }
mysql = "22.1.0"